Atoms button first commit
shinonome-inc/masami-frontend-last pull request #1
Opened 2021-05-06 18:29 UTC by kawaguchimasami

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [〇 ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか
a href を使用せよと指定がありましたが、<a href="#">コンセプト</a>とhtmlにコードするのはわかったのですが、これをCSSでコードするとき｛｝の前に該当する名前がなにかわかりませんでした。
そのため、buttonでとりあえず作りました。

ほとんど写しただけでホバー時の動作があまりよくわかっていません。

backgronud,margin ,padding など既出のものは理解していると思います。

リンク
http://localhost:61748/?path=/story/atoms-button--button
[](chromatic上の該当ページへのリンクを貼る)

2021-05-07 21:48 UTC, okathira requested changes
ホバー時の動作のについては CSS Diner で Pseudo-selector というのを見たと思うので、その辺りの**擬似クラス**を調べてみてください。
あとは以下の確認をお願いします

2021-05-07 21:48 UTC, okathira commented on src/components/_variables.scss
> +$fontfamily-esample: gothic;
https://basic-frontend.4nonome.com/lastAssignment/define_variables/
このページの作業ができてないみたいです

2021-05-07 21:48 UTC, okathira commented on src/components/_variables.scss
> +$fontfamily-esample: gothic;
コードの最後には空行を入れましょう

2021-05-09 14:58 UTC, kawaguchimasami commented on src/components/_variables.scss
> +$fontfamily-esample: gothic;
どちらも直しました

2021-05-09 15:09 UTC, kawaguchimasami reviewed
インデント、ホバー時の動作、最後の行の空白を修正しました。

2021-05-12 05:56 UTC, Yuto-tus reviewed
インデントがずれているため、ふぉーまったーを使って直してください。
よろしくお願いします。

2021-05-12 05:56 UTC, Yuto-tus commented on src/components/atoms/button/button.scss
> +    color:white;
変数指定ができてないようです。

2021-05-12 18:00 UTC, kawaguchimasami commented on src/components/atoms/button/button.scss
> +    color:white;
フォーマッタを導入しました。また、colorの変数表示をしていないのは変数が黒であるが、今回は白色で表示したいためです。

2021-05-14 19:43 UTC, kawaguchimasami commented
新しくブランチを作成しなおします

2021-05-14 19:44 UTC, kawaguchimasami commented
新しくブランチを作成しなおします

2021-05-14 19:44 UTC, closed without merging